name: ShallowLearn
channels:
  - conda-forge
dependencies:
  - python=3.10.8 
  - gdal>3.8.3
  - rasterio>1.2.8
  - libgdal>3.6.2 
  - matplotlib-base=3.10.1
  - scikit-learn=1.6.1
  - scikit-image=0.25.2
  - opencv=4.9.0
  - numpy=1.25.2
  - pytest=8.3.5
  - shapely=2.0.4
  - coverage=7.7.1
  - libtiff=4.6.0 
  - pandas=2.2.3
  - geopandas=1.0.1
  - tqdm

  
