name: ShallowLearn
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - cryptography=38.0.4
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.4.4
  - jupyter_core=5.2.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=1.0.0
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - krb5=1.19.4
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=22.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - affine==2.3.1
      - appdirs==1.4.4
      - click==8.1.3
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.0.6
      - coverage==7.2.1
      - cycler==0.11.0
      - ephem==4.1.4
      - fiona==1.8.22
      - fonttools==4.38.0
      - geopandas==0.12.1
      - imageio==2.22.4
      - importlib-metadata==5.1.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - matplotlib==3.6.2
      - munch==2.5.0
      - networkx==2.8.8
      - opencv-contrib-python==4.7.0.68
      - pandas==1.5.2
      - pandoc==2.3
      - pillow==9.3.0
      - plumbum==1.8.0
      - pycrs==1.0.2
      - pyee==8.2.2
      - pyparsing==3.0.9
      - pyperclip==1.8.2
      - pyppeteer==1.0.2
      - pyproj==3.4.0
      - pysimplegui==4.60.4
      - pyqt5-sip==12.11.0
      - python-version==0.0.2
      - pytz==2022.6
      - pywavelets==1.4.1
      - rasterio==1.3.4
      - scikit-image==0.19.3
      - scikit-learn==1.1.3
      - scipy==1.9.3
      - seaborn==0.12.1
      - shapely==1.8.5.post1
      - snuggs==1.4.7
      - threadpoolctl==3.1.0
      - tifffile==2022.10.10
      - tqdm==4.64.1
      - webpdf==1.0
      - websockets==10.4
      - xgboost==1.7.1
      - yellowbrick==1.5
      - zipp==3.11.0
      - pytest==7.3.1